version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
        versions:
          - ">=7"
    groups:
      development-dependencies:
        dependency-type: development
